import type {Metadata} from "next";
import "./globals.scss";

import {Inter} from "next/font/google";
import AppWalletProvider from "@/app/components/AppWalletProvider";

const inter = Inter({subsets: ["latin"]});


export const metadata: Metadata = {
    title: "Contribo",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${inter.className} antialiased`}>
            <a className="sr-only sr-only-focusable" href="#main">Skip to main content</a>
            <AppWalletProvider>
                {children}
            </AppWalletProvider>
        </body>
        </html>
);
}
