[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
contribute = "7mHhw5gkkVX59KvbpHCF4fumCRQtTDwEAzWJN5K1q8if"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "wallet-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
