[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
claim_refund = "Hwf1yAEfibNzxB1UR3HNKGDPEGcaQEKScZYugZyrqeeE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "wallet-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
setup-pool = "ts-node scripts/setup-pool.ts"
